//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestHubService
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_credit_card
    {
        public int credit_card_id { get; set; }
        public int customer_id { get; set; }
        public int billing_address_id { get; set; }
        public string cc_type { get; set; }
        public string cc_number { get; set; }
        public System.DateTime cc_expiration { get; set; }
        public string cvv_number { get; set; }
        public string cc_name { get; set; }
    }
}
