//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestHubService
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurant_order_items
    {
        public int order_item_id { get; set; }
        public int order_id { get; set; }
        public int menu_item_id { get; set; }
        public int menu_item_quantity { get; set; }
        public decimal menu_item_final_price { get; set; }
    }
}
