//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestHubService
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurant_orders
    {
        public int order_id { get; set; }
        public int customer_id { get; set; }
        public int restaurant_branch_id { get; set; }
        public System.DateTime order_date_time { get; set; }
        public System.DateTime pickup_date_time { get; set; }
        public string order_status { get; set; }
        public decimal subtotal { get; set; }
        public decimal tax { get; set; }
        public decimal discount { get; set; }
        public decimal total_charged { get; set; }
    }
}
