//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestHubService
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurant_branch
    {
        public int restaurant_branch_id { get; set; }
        public string restaurant_name { get; set; }
        public string street_address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip_code { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string branch_manager_name { get; set; }
        public string branch_manager_email { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public bool public_visibility_status { get; set; }
        public bool admin_approval_status { get; set; }
        public string restaurant_photo { get; set; }
    }
}
